### ISSUE TITLE
Has any one built and ran this?

### ISSUE THREAD

**Issue by aivijay** [kevinwchn/slamit_ORBSLAM2_on_Android#3]
Has anyone build this app fully including the c++ modules and have ran it successfully. I have got it build and am able to initialize the slam. But I don't see any tracking even after long periods of time. The video shows tracking and plotting starts after a few seconds. But I never was able to get the application to generate the point cloud to plot. Any ideas?? By the way, what are those 3 buttons at the bottom? What do the calibration button do especially?

**Comment by aivijay** [comment]
Ahh, I just got it working finally.

**Comment by jingedawang** [comment]
How did you set the calibration file?
I was really in trouble with the calibration file. I don't know what format it is.

**Comment by aivijay** [comment]
Use one from https://github.com/raulmur/ORB_SLAM2/tree/master/Examples/Monocular
Eg.,TUM1.yaml.

Usually it should work as it is by itself. But to calibrate your devices camera, you will have to use OpenCV's calibration program or so, so you can get proper values for the following

Camera.fx: 517.306408
Camera.fy: 516.469215
Camera.cx: 318.643040
Camera.cy: 255.313989

Camera.k1: 0.262383
Camera.k2: -0.953104
Camera.p1: -0.005358
Camera.p2: 0.002628
Camera.k3: 1.163314

Substitute the as needed once generated from the calibration file from OpenCV.

**Comment by aivijay** [comment]
Also refer to OpenCV's matrix returns to map the values for fx, fy, cx and cy etc. Usually when calibrated you will have two matrices as the output. The first one will be 3x3 matrix which will give you fx, fy, cx and cy. The second will be a single row matrix mapping k1, k2 I think.

**Comment by aivijay** [comment]
Also refer to https://github.com/aivijay/slamit_ORBSLAM2_on_Android which I tweaked various things and added some more documentation.

**Comment by BrianT34** [comment]
Hi @aivijay, thanks for sharing your experience. Wonder if you have encountered this issue while building the project. I installed opencv manager 2.4.9. But it keeps crashing. May I know how you resolve the issue? Thanks.

**Comment by serviceberry3** [comment]
I'm also having a crashing issue: in ORBSLAMForTestActivity, the line System.loadLibrary("ORB_SLAM2_EXCUTOR");
is failing with
java.lang.UnsatisfiedLinkError: dlopen failed: library "libORB_SLAM2_EXCUTOR.so" not found

Any ideas? Not sure why it wouldn't be found. libORB_SLAM2_EXCUTOR.so is located in my jniLibs/armeabi-v7a folder.
